import type { StyleOption } from '@/entities/avatar'

export const STYLE_OPTIONS: StyleOption[] = [
  {
    id: 'ghibli',
    label: '지브리풍',
    emoji: '🌿',
    description: '따뜻하고 자연스러운\n지브리 스타일',
    gradient: 'from-emerald-400 to-teal-500',
  },
  {
    id: 'disney',
    label: '디즈니풍',
    emoji: '⭐',
    description: '귀엽고 사랑스러운\n디즈니/주토피아 스타일',
    gradient: 'from-sky-400 to-blue-500',
  },
  {
    id: 'hanbok',
    label: '한복/전통',
    emoji: '🎎',
    description: '아름다운 한국 전통\n한복 스타일',
    gradient: 'from-rose-400 to-pink-500',
  },
  {
    id: 'game',
    label: '게임 캐릭터',
    emoji: '🎮',
    description: '멋진 RPG 게임\n캐릭터 스타일',
    gradient: 'from-violet-500 to-purple-600',
  },
  {
    id: 'watercolor',
    label: '수채화풍',
    emoji: '🎨',
    description: '부드럽고 감성적인\n수채화 일러스트 스타일',
    gradient: 'from-amber-400 to-orange-500',
  },
  {
    id: 'studio',
    label: '스튜디오',
    emoji: '📸',
    description: '전문 AI 아트\n스튜디오 스타일',
    gradient: 'from-slate-500 to-gray-700',
  },
]

export const AGE_GROUPS = [
  { value: '0-7', label: '0~7세', emoji: '🐣' },
  { value: '8-13', label: '8~13세', emoji: '🌟' },
  { value: '14-19', label: '14~19세', emoji: '🔥' },
  { value: '20+', label: '20세 이상', emoji: '✨' },
] as const

export const GENDER_OPTIONS = [
  { value: 'male', label: '남자', emoji: '👦' },
  { value: 'female', label: '여자', emoji: '👧' },
] as const

export const NICKNAME_SUGGESTIONS = [
  '별빛전사',
  '구름탐험가',
  '달빛요정',
  '바람의기사',
  '불꽃영웅',
  '시간여행자',
  '빛의수호자',
  '꿈의탐험가',
  '우주대장',
  '은하수여왕',
  '천둥번개',
  '무지개전사',
  '바다의수호자',
  '숲의정령',
  '용의기사',
  '별자리왕',
  '얼음요정',
  '화염용사',
  '바람요정',
  '황금독수리',
  '은빛늑대',
  '하늘천사',
  '번개소녀',
  '폭풍기사',
  '달의여신',
  '태양용사',
  '별의왕자',
  '마법소녀',
  '전설의검사',
  '우주비행사',
  '드래곤테이머',
  '슈퍼히어로',
  '미래전사',
  '빛나는별',
  '꿈꾸는아이',
  '신비한마법사',
  '보라빛요정',
  '황금기사',
  '은하대장',
  '달빛전사',
  '불꽃마법사',
  '무적전사',
  '별의요정',
  '구름왕자',
  '천상의기사',
  '신비한탐험가',
  '빛나는용사',
  '꿈의기사',
  '하늘의수호자',
  '땅의거인',
  '바다의용사',
  '숲의마법사',
  '불꽃기사',
  '얼음마법사',
  '번개기사',
  '황금요정',
  '은빛기사',
  '별빛마법사',
  '달빛마법사',
  '태양기사',
  '무지개마법사',
  '바람기사',
  '우주탐험가',
  '시간마법사',
  '꿈의요정',
  '별자리용사',
  '은하수기사',
  '천둥마법사',
  '번개요정',
  '화염마법사',
  '얼음기사',
  '바다요정',
  '숲의기사',
  '황금용사',
  '은빛전사',
  '별의기사',
  '달의기사',
  '태양의수호자',
  '무지개기사',
  '바람용사',
  '신비전사',
  '마법왕자',
  '빛의요정',
  '꿈의왕자',
  '별나라대장',
  '유니콘기사',
  '드래곤슬레이어',
  '피닉스전사',
  '크리스탈마법사',
  '다이아몬드기사',
  '폭풍용사',
  '바람의요정',
  '빛의기사',
  '별빛용사',
  '구름마법사',
  '달빛기사',
  '불꽃요정',
  '하늘기사',
  '대지의수호자',
  '물의요정',
]

export const LOADING_MESSAGES = [
  { text: '마법을 모으는 중...', emoji: '✨' },
  { text: '색을 칠하는 중...', emoji: '🎨' },
  { text: '캐릭터를 깨우는 중...', emoji: '🌟' },
  { text: '마법의 옷을 입히는 중...', emoji: '👑' },
  { text: '눈을 반짝반짝 빛내는 중...', emoji: '💫' },
  { text: '머리카락을 다듬는 중...', emoji: '✂️' },
  { text: '마지막 마법 터치 중...', emoji: '🪄' },
  { text: '거의 다 됐어요!', emoji: '🎉' },
]

export const AIKON_RANGE = { min: 500, max: 899 }
